test:
  before_script:
    - virtualenv --python=`which python3` ptp-sim-test
    - source ptp-sim-test/bin/activate
    - pip install -r requirements.txt
  script:
    - python -m unittest discover
  after_script:
    - deactivate
  tags:
    - ptp

