before_script:
  - virtualenv --python=`which python3` ptp-env
  - source ptp-env/bin/activate
  - pip install -r requirements.txt

after_script:
  - deactivate

variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"

cache:
  key: "pip-requirements"
  paths:
    - .cache/pip
    - ptp-env/

test:
  script:
    - python -m unittest discover
  tags:
    - ptp

acquisition:
  script:
    - source /opt/Xilinx/Vivado/2016.4/settings64.sh
    - git clone --recurse-submodules https://gitlab.lasse.ufpa.br/2014-fronthaul/synchronization/roe_vivado.git
    - ./capture.py -vvv --fh-traffic --n-rru-dl 2 --n-rru-ul 2 --n-rru-ptp 2 -p -c -y --roe-path roe_vivado/
  only:
    refs:
      - schedules
      - web
  tags:
    - ptp

.api:
  only:
    changes:
      - api/**/*
  tags:
    - ptp

api_image:
  extends: .api
  stage: build
  script:
    - docker-compose -f api/docker/docker-compose.yml build

api_test:
  extends: .api
  stage: test
  script:
    - python -m unittest discover -s api

api_deploy:
  extends: .api
  stage: deploy
  before_script:
    - docker-compose -f api/docker/docker-compose.yml down -v
  script:
    - docker-compose -f api/docker/docker-compose.yml up -d
