before_script:
  - virtualenv --python=`which python3` ptp-env
  - source ptp-env/bin/activate
  - pip install -r requirements.txt

after_script:
  - deactivate

variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"

cache:
  key: "pip-requirements"
  paths:
    - .cache/pip
    - ptp-env/

stages:
  - test
  - build
  - deploy
  - capture

test:
  script:
    - python -m unittest discover
  tags:
    - ptp

.api:
  rules:
    - if: '$CI_PIPELINE_SOURCE == "web"'
      when: manual
      allow_failure: true
    - if: '$CI_PIPELINE_SOURCE == "schedule"'
      when: never
    - changes:
      - "api/**/*"
      when: on_success
    - when: never
  tags:
    - ptp

api_image:
  extends: .api
  stage: build
  script:
    - docker-compose -f api/docker/docker-compose.yml build

api_test:
  extends: .api
  stage: test
  script:
    - python -m unittest discover -s api

api_deploy:
  extends: .api
  stage: deploy
  before_script:
    - docker-compose -f api/docker/docker-compose.yml down -v
  script:
    - docker-compose -f api/docker/docker-compose.yml up -d
