version: '3.7'

services:
  api:
    image: lasse/ptp-api:latest
    build:
      context: ../../
      dockerfile: api/docker/Dockerfile
    volumes:
      - datasets:/app/api/datasets/
    ports:
      - 10098:80
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=ptp
      - DB_PW=${DB_PW}
      - DB_NAME=ptp
    depends_on:
      - db
    restart: always
  db:
    image: postgres:9.6.17
    volumes:
      - database:/var/lib/postgresql/data/
    ports:
      - 10099:5432
    environment:
      - POSTGRES_USER=ptp
      - POSTGRES_PASSWORD=${DB_PW}
      - POSTGRES_DB=ptp
    restart: always

volumes:
  datasets:
    driver_opts:
      type: none
      device: /opt/ptp_datasets/
      o: bind
  database:

