name: Tests

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 yapf
        pip install -r test-requirements.txt
    - name: Lint with flake8
      run: |
        flake8 .
    - name: Check formatting
      run: |
        yapf --diff --recursive --verbose ptp/
    - name: Unit tests
      run: |
        python -m unittest discover
